[COMMENT]
Comment=No comment entered.
RecordAnnotation=
[EXPORTINFO]
Type=jpg
Name=1600us_750C_50ms
[CAMERA]
Manufacturer=Mikrotron GmbH
Model=MotionBLITZ EoSens mini2
Framerate=5000
Shuttertime=10
Serial=00122
Firmware=B2.03-F0.84-V4.68
[RECORD]
StartTime=06.09.2018 15:18:39
ImageCount=401
[IMAGEDESCRIPTION]
ImageWidth=256
ImageHeight=764
ImageFormat=GRAY8
[SEQUENCEINFORMATION]
NumberofFrames_00=401
TriggerFrameNumber_00=-675
TriggerRefTime_00=1731,3296
[EXPORTEDIMAGES]
0=5300-5700:401
