[COMMENT]
Comment=No comment entered.
RecordAnnotation=
[EXPORTINFO]
Type=jpg
Name=1400us_750C_50ms
[CAMERA]
Manufacturer=Mikrotron GmbH
Model=MotionBLITZ EoSens mini2
Framerate=5000
Shuttertime=10
Serial=00122
Firmware=B2.03-F0.84-V4.68
[RECORD]
StartTime=06.09.2018 14:43:47
ImageCount=501
[IMAGEDESCRIPTION]
ImageWidth=256
ImageHeight=764
ImageFormat=GRAY8
[SEQUENCEINFORMATION]
NumberofFrames_00=501
TriggerFrameNumber_00=-575
TriggerRefTime_00=1027,51488
[EXPORTEDIMAGES]
0=5200-5700:501
